clear mex

kBuildFolder = './c++/build';
if (~exist(kBuildFolder, 'dir'))
  mkdir(kBuildFolder);
end;

mex ./c++/cnntrain_mex.cpp ...
    "./c++/sources/*.cpp" ...
    -I"./c++/include/" ...      
    -lut ...
    -outdir ./c++/build ...   
    -largeArrayDims;
disp('cnntrain_mex compiled');  

mex ./c++/classify_mex.cpp ...
    "./c++/sources/*.cpp" ...
    -I"./c++/include/" ...      
    -lut ...
    -outdir ./c++/build ...   
    -largeArrayDims;
disp('classify_mex compiled');

mex ./c++/genweights_mex.cpp ...
    "./c++/sources/*.cpp" ...
    -I"./c++/include/" ...      
    -lut ...
    -outdir ./c++/build ...   
    -largeArrayDims;
disp('genweights_mex compiled');
