clear mex

mex ./c++/cnntrain_mex.cpp ./c++/sources/*.cpp ...
  -largeArrayDims ...
  -I"./c++/include/" ...
  -I"C:\Program Files\Boost\include\boost-1_54" ...
  -L"C:\Program Files\Boost\lib" ...
  -outdir ./c++/build

mex ./c++/classify_mex.cpp ./c++/sources/*.cpp ...
  -largeArrayDims ...
  -I"./c++/include/" ...
  -I"C:\Program Files\Boost\include\boost-1_54" ...
  -L"C:\Program Files\Boost\lib" ...
  -outdir ./c++/build

mex ./c++/genweights_mex.cpp ./c++/sources/*.cpp ...
  -largeArrayDims ...
  -I"./c++/include/" ...
  -I"C:\Program Files\Boost\include\boost-1_54" ...
  -L"C:\Program Files\Boost\lib" ...
  -outdir ./c++/build
